System.register("chunks:///PlayerCtl.js",["./_virtual/_rollupPluginBabelHelpers.js","cc"],(function(e,t){var o,i,n,r,l,a,s,c,u,_,d,h,p,v,y,f,m,g,k,A,C,b,w,P;return e({_dec:void 0,_dec2:void 0,_dec3:void 0,_class:void 0,_class2:void 0,_descriptor:void 0,_descriptor2:void 0,_temp:void 0}),{setters:[function(e){o=e.applyDecoratedDescriptor,i=e.inherits,n=e.createClass,r=e.classCallCheck,l=e.possibleConstructorReturn,a=e.getPrototypeOf,s=e.initializerDefineProperty,c=e.assertThisInitialized},function(e){u=e.cclegacy,_=e._decorator,d=e.Node,h=e.Vec3,p=e.SkeletalAnimationComponent,v=e.macro,y=e.Component}],execute:function(){u._RF.push({},"0e1e3je6dRFh53c2YmT4sjs","PlayerCtl",void 0),.016,150,w=_.ccclass,P=_.property,e("PlayerCtl",(f=w("PlayerCtl"),m=P(d),g=P(d),f((C=o((A=function(e){function t(){var e,o;r(this,t);for(var i=arguments.length,n=new Array(i),u=0;u<i;u++)n[u]=arguments[u];return o=l(this,(e=a(t)).call.apply(e,[this].concat(n))),s(o,"node_role",C,c(o)),s(o,"node_camera",b,c(o)),o._vector=h.ZERO,o._vectorAngle=h.ZERO,o._now_time=0,o}return i(t,e),n(t,[{key:"onLoad",value:function(){this._skeletal=this.node_role.getComponent(p)}},{key:"joysitckCallback",value:function(e,t){h.rotateZ(e,e,h.ZERO,this.node_camera.eulerAngles.y*v.RAD),this._vector=e.normalize(),t&&(this.node_role.eulerAngles=new h(0,t+90+this.node_camera.eulerAngles.y,0))}},{key:"joysitckAngleCallback",value:function(e,t){this._vectorAngle=e.normalize()}},{key:"fix_update",value:function(e){this._vector.lengthSqr()>0?(this.node.setPosition(this.node.position.add3f(150*this._vector.x*e,0,150*-this._vector.y*e)),this._skeletal.resume()):this._skeletal.pause(),this._vectorAngle.lengthSqr()>0&&(this.node_camera.eulerAngles=this.node_camera.eulerAngles.add3f(0,-this._vectorAngle.x,0))}},{key:"update",value:function(e){for(this._now_time+=e;this._now_time>=.016;)this.fix_update(.016),this._now_time-=.016}}]),t}(y)).prototype,"node_role",[m],{configurable:!0,enumerable:!0,writable:!0,initializer:function(){return null}}),b=o(A.prototype,"node_camera",[g],{configurable:!0,enumerable:!0,writable:!0,initializer:function(){return null}}),k=A))||k)),u._RF.pop()}}}));

System.register("chunks:///joystick.js",["./_virtual/_rollupPluginBabelHelpers.js","cc"],(function(t,o){var e,i,n,r,a,c,s,l,u,h,p,y,d,v,f,m,T,k,_,g,C,B,b,j,E,N,x,R;return t({_dec:void 0,_dec2:void 0,_dec3:void 0,_dec4:void 0,_class:void 0,_class2:void 0,_descriptor:void 0,_descriptor2:void 0,_descriptor3:void 0,_descriptor4:void 0,_temp:void 0}),{setters:[function(t){e=t.applyDecoratedDescriptor,i=t.inherits,n=t.createClass,r=t.classCallCheck,a=t.possibleConstructorReturn,c=t.getPrototypeOf,s=t.initializerDefineProperty,l=t.assertThisInitialized},function(t){u=t.cclegacy,h=t._decorator,p=t.Node,y=t.UITransformComponent,d=t.Vec3,v=t.macro,f=t.Component}],execute:function(){u._RF.push({},"853a3N/NYBF6J5mTqZyLlqd","joystick",void 0),N=h.ccclass,x=h.property,m=x({type:p,tooltip:"移动中心节点"}),T=x({type:p,tooltip:"摇杆背景节点"}),k=x({type:cc.Integer,tooltip:"摇杆活动半径"}),_=x({type:[cc.Component.EventHandler],tooltip:"摇杆移动回调"}),R=N((B=e((C=function(t){function o(){var t,e;r(this,o);for(var i=arguments.length,n=new Array(i),u=0;u<i;u++)n[u]=arguments[u];return e=a(this,(t=c(o)).call.apply(t,[this].concat(n))),s(e,"midNode",B,l(e)),s(e,"joyBk",b,l(e)),s(e,"maxR",j,l(e)),s(e,"joyCallBack",E,l(e)),e.uITransform=null,e}return i(o,t),n(o,[{key:"onLoad",value:function(){this.goBackMid()}},{key:"start",value:function(){this.uITransform=this.getComponent(y),this.joyBk.on(p.EventType.TOUCH_START,this.onTouchStart,this),this.joyBk.on(p.EventType.TOUCH_MOVE,this.onTouchMove,this),this.joyBk.on(p.EventType.TOUCH_END,this.onTouchEnd,this),this.joyBk.on(p.EventType.TOUCH_CANCEL,this.onTouchEnd,this)}},{key:"goBackMid",value:function(){this.midNode.setPosition(0,0,0)}},{key:"onTouchStart",value:function(t){this.onTouchMove(t)}},{key:"onTouchMove",value:function(t){var o=t.getUILocation(),e=this.uITransform.convertToNodeSpaceAR(new d(o.x,o.y));this.clampPos(e),this.midNode.setPosition(e.x,e.y,0);var i=this.covertToAngle(e);this.joyCallBack.forEach((function(t){return t.emit([e,i])}))}},{key:"onTouchEnd",value:function(t){this.goBackMid(),this.joyCallBack.forEach((function(t){return t.emit([new d(0,0,0)])}))}},{key:"clampPos",value:function(t){var o=t.length();if(o>this.maxR){var e=this.maxR/o;t.x*=e,t.y*=e}}},{key:"covertToAngle",value:function(t){return Math.atan2(t.y,t.x)*v.DEG}}]),o}(f)).prototype,"midNode",[m],{configurable:!0,enumerable:!0,writable:!0,initializer:function(){return null}}),b=e(C.prototype,"joyBk",[T],{configurable:!0,enumerable:!0,writable:!0,initializer:function(){return null}}),j=e(C.prototype,"maxR",[k],{configurable:!0,enumerable:!0,writable:!0,initializer:function(){return 100}}),E=e(C.prototype,"joyCallBack",[_],{configurable:!0,enumerable:!0,writable:!0,initializer:function(){return[]}}),g=C))||g,u._RF.pop(),t("default",R)}}}));

System.register("chunks:///_virtual/prerequisite-imports:main",["../PlayerCtl.js","../joystick.js"],(function(t,e){return{setters:[function(t){},function(t){}],execute:function(){}}}));

(function(r) {
  r('project:///assets/src/PlayerCtl.js', 'chunks:///PlayerCtl.js');
  r('project:///assets/src/joystick.js', 'chunks:///joystick.js');
  r('virtual:///prerequisite-imports:main', 'chunks:///_virtual/prerequisite-imports:main'); 
})(function(mid, cid) {
    System.register(mid, [cid], function (_export, _context) {
    var _m;
    return {
        setters: [function(m) { _m = m; }],
        execute: function () { _export(_m); }
    };
    });
});